<table>
<table class="top_16"cellpadding="10">
  <tr>
    <th>IDRECURSO</th>
    <th>NOMBRE</th>
    <th>VERSION</th>
    
  </tr>
  
  <tr>
	<?php 
	$tablaRecurso=new Application_Model_DbTable_Recurso();
	$ver=$tablaRecurso->fetchAll();
	//$ver=$this->verproyectos;
	
	
	foreach ($ver as $fila)
	{
		echo"<td>".$fila->idrecurso."</td>";
		echo"<td>".$fila->nombre."</td>";
		echo"<td>".$fila->version."</tr>";
		
		
		
		
		
	}

?>

</table>
</tr>

	
	
    



